theme: osuny
_merge: deep
params:
  plausible: ecocean.fr
  summary:
    position: hero
  search:
    active: true
  logo:
    footer: '/assets/images/logo-footer.svg'
  i18n:
    positions:
      - primary
  menu:
    primary:
      level_2:
        summary:
        title:
          active: true
  home:
    head:
      title: site
  organizations:
    prefer_image_over_logo: true
    index:
      taxonomies:
        display: false
    single:
      backlinks: true
  persons:
    index:
      taxonomies:
        display: false
  posts:
    index:
      layout: grid
  projects:
    index:
      layout: list
      options:
        year: true